.\"Copyright 2010 (c) EPFL
.TH XDF_COPY_CHCONF 3 2010 "EPFL" "xdffileio library manual"
.SH NAME
xdf_copy_chconf - Configure a channel according to a template
.SH SYNOPSIS
.LP
.B #include <xdfio.h>
.sp
.BI "int xdf_copy_chconf(struct xdfch* " dst ", const struct xdfch* " src ");"
.br
.SH DESCRIPTION
.LP
\fBxdf_copy_chconf\fP() configure the channel referenced by \fIdst\fP using the information described by \fIsrc\fP.
.SH "RETURN VALUE"
.LP
The function returns 0 in case of success, -1 otherwise.
.SH "SEE ALSO"
.BR xdf_set_chconf (3),
.BR xdf_get_chconf (3)

