.\"Copyright 2010 (c) EPFL
.TH XDF_GET_CHANNEL 3 2010 "EPFL" "xdffileio library manual"
.SH NAME
xdf_get_channel - Get the channel descriptor handle of a particular index
.SH SYNOPSIS
.LP
.B #include <xdfio.h>
.sp
.BI "hchxdf xdf_get_channel(hxdf " xdf ", unsigned int " index ");"
.br
.SH DESCRIPTION
.LP
\fBxdf_get_channel\fP() gets the channel descriptor of the channel stored at
index \fIindex\fP in the XDF file referenced by the handle \fIxdf\fP.
.SH "RETURN VALUE"
.LP
\fBxdf_get_channel\fP() returns the handle to requested channel descriptor in
case of success, NULL otherwise.
.SH "SEE ALSO"
.BR xdf_add_channel (3)


