.\"Copyright 2010 (c) EPFL
.TH XDF_GET_EVTTYPE 3 2010 "EPFL" "xdffileio library manual"
.SH NAME
xdf_get_evttype - Get information about an event type
.SH SYNOPSIS
.LP
.B #include <xdfio.h>
.sp
.BI "int xdf_get_evttype(struct xdf* " xdf ", unsigned int " evttype ","
.br
.BI "                    int* " code ", const char** " desc ");"
.br
.SH DESCRIPTION
.LP
\fBxdf_get_evttype\fP() returns the information of the event type
\fIevttype\fP of the XDF file referenced by \fIxdf\fP. The code and the
description of the event type are returned respectively in the pointers
\fIcode\fP and \fIdesc\fP.
.SH "RETURN VALUE"
.LP
The function returns 0 in case of success. Otherwise -1 is returned and
\fIerrno\fP is set appropriately.
.SH ERRORS
.TP
.B EINVAL
\fIxdf\fP, \fIcode\fP or \fIdesc\fP is NULL.
.TP
.B ERANGE
\fIevttype\fP is an invalid event type of \fIxdf\fP
.SH "SEE ALSO"
.BR xdf_get_event (3)



