.\"Copyright 2010 (c) EPFL
.TH XDF_COPY_CONF 3 2010 "EPFL" "xdffileio library manual"
.SH NAME
xdf_copy_conf - Configure a xDF file according to a template
.SH SYNOPSIS
.LP
.B #include <xdfio.h>
.sp
.BI "int xdf_copy_conf(struct xdf* " dst ", conf struct xdf* " src ");"
.br
.SH DESCRIPTION
.LP
\fBxdf_copy_conf\fP() configure the xDF file referenced by \fIdst\fP using the information described by \fIsrc\fP.
.SH "RETURN VALUE"
.LP
The function returns 0 in case of success, \-1 otherwise.
.SH "SEE ALSO"
.BR xdf_set_conf (3),
.BR xdf_get_conf (3)


